# Generated by Django 4.2.3 on 2023-09-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unmane', models.CharField(max_length=50)),
                ('upassword', models.CharField(max_length=50)),
                ('uemail', models.CharField(max_length=50)),
            ],
        ),
    ]
